name: Scheduled Run

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  scheduled_run:
    name: Scheduled Run
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.x
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Build SpotifySync
        run: dotnet build .\SpotifySync\SpotifySync.csproj --configuration Release
        env:
          DOTNET_NOLOGO: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Run SpotifySync
        run: .\SpotifySync\bin\Release\netcoreapp3.1\SpotifySync.exe
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_TOKEN: ${{ secrets.SPOTIFY_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
